# Generated by Django 3.2.12 on 2022-02-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_django_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='Imagesss')),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='img',
        ),
    ]
